[package]
name = "shamash"
version = "0.7.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nabu = { git = "https://github.com/Xqhare/nabu" }
signal-hook = "0.3.17"
horae = { git = "https://github.com/Xqhare/horae" }

[profile.release]
lto = true
